version: "3"

services:
  moonship:
    image: .
    container_name: moonship
    environment:
      - "AWS_S3_KEY_ID=${AWS_S3_KEY_ID}"
      - "AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}"
      - "AWS_S3_PATH=${AWS_S3_PATH}"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "Moonship"
    restart: always
